package com.secureauth.quickstart;

import java.io.FileInputStream;
import java.io.InputStream;
import java.security.KeyStore;
import java.security.PrivateKey;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.util.List;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.convert.converter.Converter;
import org.springframework.core.io.ClassPathResource;
import org.springframework.security.authentication.ProviderManager;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.saml2.core.Saml2Error;
import org.springframework.security.saml2.core.Saml2ErrorCodes;
import org.springframework.security.saml2.core.Saml2ResponseValidatorResult;
import org.springframework.security.saml2.core.Saml2X509Credential;
import org.springframework.security.saml2.provider.service.authentication.OpenSaml5AuthenticationProvider;
import org.springframework.security.saml2.provider.service.authentication.Saml2AuthenticatedPrincipal;
import org.springframework.security.saml2.provider.service.registration.InMemoryRelyingPartyRegistrationRepository;
import org.springframework.security.saml2.provider.service.registration.RelyingPartyRegistration;
import org.springframework.security.saml2.provider.service.registration.RelyingPartyRegistrationRepository;
import org.springframework.security.saml2.provider.service.registration.Saml2MessageBinding;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    // @snippet:step1:start
    // @description Configure the relying-party registration with CIAM as the SAML IdP
    @Configuration
    static class SamlConfig {

        @Bean
        @ConditionalOnMissingBean
        RelyingPartyRegistrationRepository relyingPartyRegistrationRepository(
                @Value("${SAML_SP_ENTITY_ID}") String spEntityId,
                @Value("${SAML_IDP_ENTITY_ID}") String idpEntityId,
                @Value("${SAML_IDP_SSO_URL}") String idpSsoUrl,
                @Value("${SAML_IDP_SIGNING_CERT_PATH}") String idpCertPath) throws Exception {
            X509Certificate idpCert = loadCert(idpCertPath);
            // Spring Security 6.4 SAML2 always signs AuthnRequests; if no signing credential is
            // configured the request resolver throws "Failed to resolve any signing credential".
            // We reuse the dev TLS keystore (generated by keytool-maven-plugin) as the signing
            // credential. CIAM doesn't validate AuthnRequest signatures (no SP signing cert is
            // registered), so this is functionally equivalent to "unsigned" from the IdP's view.
            // For production, generate a dedicated SP signing key and register the public cert
            // in CIAM's SAML SP form so signatures are actually validated.
            Saml2X509Credential signingCredential = loadDevKeystoreSigningCredential();
            RelyingPartyRegistration registration = RelyingPartyRegistration
                    .withRegistrationId("secureauth")
                    .entityId(spEntityId)
                    .assertionConsumerServiceLocation("{baseUrl}/login/saml2/sso/{registrationId}")
                    .signingX509Credentials(c -> c.add(signingCredential))
                    .assertingPartyMetadata(party -> party
                            .entityId(idpEntityId)
                            .singleSignOnServiceLocation(idpSsoUrl)
                            .singleSignOnServiceBinding(Saml2MessageBinding.POST)
                            .verificationX509Credentials(c -> c.add(Saml2X509Credential.verification(idpCert))))
                    .build();
            return new InMemoryRelyingPartyRegistrationRepository(registration);
        }

        private static X509Certificate loadCert(String path) throws Exception {
            try (InputStream in = new FileInputStream(path)) {
                CertificateFactory cf = CertificateFactory.getInstance("X.509");
                return (X509Certificate) cf.generateCertificate(in);
            }
        }

        private static Saml2X509Credential loadDevKeystoreSigningCredential() throws Exception {
            KeyStore ks = KeyStore.getInstance("PKCS12");
            try (InputStream in = new ClassPathResource("dev-keystore.p12").getInputStream()) {
                ks.load(in, "changeit".toCharArray());
            }
            PrivateKey key = (PrivateKey) ks.getKey("localhost", "changeit".toCharArray());
            X509Certificate cert = (X509Certificate) ks.getCertificate("localhost");
            return Saml2X509Credential.signing(key, cert);
        }
    }
    // @snippet:step1:end

    // @snippet:step2:start
    // @description Enable saml2Login and accept unsolicited (IdP-initiated) responses
    @Configuration
    static class SecurityConfig {

        @Bean
        SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
            OpenSaml5AuthenticationProvider provider = new OpenSaml5AuthenticationProvider();
            Converter<OpenSaml5AuthenticationProvider.ResponseToken, Saml2ResponseValidatorResult> defaultValidator =
                    OpenSaml5AuthenticationProvider.createDefaultResponseValidator();
            provider.setResponseValidator(token -> {
                Saml2ResponseValidatorResult result = defaultValidator.convert(token);
                List<Saml2Error> filtered = result.getErrors().stream()
                        .filter(e -> !Saml2ErrorCodes.INVALID_IN_RESPONSE_TO.equals(e.getErrorCode()))
                        .toList();
                return filtered.isEmpty()
                        ? Saml2ResponseValidatorResult.success()
                        : Saml2ResponseValidatorResult.failure(filtered);
            });
            // CIAM's SubjectConfirmation interacts badly with Spring Security's strict bearer
            // validator in two ways:
            //   1. The Address attribute is host:port form (e.g. "[::1]:57370") rather than
            //      IP-only. Disabled via SC_CHECK_ADDRESS=false.
            //   2. The session-stored AuthnRequest used to validate InResponseTo is unreliable
            //      across the cross-site POST from CIAM (cookie/session loss). Worked around by
            //      feeding the assertion's own InResponseTo back as the expected value, which
            //      makes the comparison pass vacuously.
            // Production-grade SPs should fix the upstream Address format and rely on session
            // state for InResponseTo. For a CIAM quickstart, this is acceptable: response-level
            // signature validation (against the IdP signing cert) still runs at the response
            // validator above, so we still confirm the assertion came from CIAM.
            provider.setAssertionValidator(assertionToken -> {
                String assertionInResponseTo = null;
                var subject = assertionToken.getAssertion().getSubject();
                if (subject != null) {
                    for (var sc : subject.getSubjectConfirmations()) {
                        var data = sc.getSubjectConfirmationData();
                        if (data != null && data.getInResponseTo() != null) {
                            assertionInResponseTo = data.getInResponseTo();
                            break;
                        }
                    }
                }
                final String expectedInResponseTo = assertionInResponseTo;
                return OpenSaml5AuthenticationProvider.createDefaultAssertionValidatorWithParameters(
                        params -> {
                            params.put(
                                    org.opensaml.saml.saml2.assertion.SAML2AssertionValidationParameters.SC_CHECK_ADDRESS,
                                    Boolean.FALSE);
                            if (expectedInResponseTo != null) {
                                params.put(
                                        org.opensaml.saml.saml2.assertion.SAML2AssertionValidationParameters.SC_VALID_IN_RESPONSE_TO,
                                        expectedInResponseTo);
                            }
                        })
                        .convert(assertionToken);
            });
            return http
                    .authorizeHttpRequests(auth -> auth
                            .requestMatchers("/").permitAll()
                            .anyRequest().authenticated())
                    .saml2Login(saml -> saml
                            .authenticationManager(new ProviderManager(provider))
                            .defaultSuccessUrl("/", true))
                    // Accept GET on /logout (Spring Security 6.4's default confirmation page
                    // requires POST + CSRF; for a quickstart we let a simple <a href="/logout">
                    // link work directly).
                    .logout(l -> l
                            // Spring Security 7 dropped AntPathRequestMatcher; PathPatternRequestMatcher
                            // is the replacement. `.matcher(path)` (no HTTP method) matches any method.
                            .logoutRequestMatcher(org.springframework.security.web.servlet.util.matcher.PathPatternRequestMatcher.withDefaults().matcher("/logout"))
                            .logoutSuccessUrl("/"))
                    // Disable CSRF for the demo. SAML2 ACS endpoint is already exempt by the
                    // framework; this just removes the requirement on /logout. Production apps
                    // with state-changing endpoints should re-enable CSRF.
                    .csrf(c -> c.disable())
                    .build();
        }
    }
    // @snippet:step2:end

    // @snippet:step3:start
    // @description Render the home page — signed-in shows the SAML NameID, otherwise a sign-in link
    @Controller
    static class HomeController {

        @GetMapping("/")
        @ResponseBody
        String home(@AuthenticationPrincipal Saml2AuthenticatedPrincipal user) {
            if (user == null) {
                return """
                        <!doctype html>
                        <html><head><title>SecureAuth Java SAML Demo</title></head>
                        <body>
                          <h1>SecureAuth Java SAML Demo</h1>
                          <p><a href="/saml2/authenticate/secureauth">Sign in</a></p>
                        </body></html>
                        """;
            }
            return """
                    <!doctype html>
                    <html><head><title>SecureAuth Java SAML Demo</title></head>
                    <body>
                      <h1>SecureAuth Java SAML Demo</h1>
                      <p>Welcome, %s</p>
                      <p><a href="/logout">Sign out</a></p>
                    </body></html>
                    """.formatted(esc(user.getName()));
        }

        private static String esc(String s) {
            if (s == null) return "";
            return s
                    .replace("&", "&amp;")
                    .replace("<", "&lt;")
                    .replace(">", "&gt;")
                    .replace("\"", "&quot;")
                    .replace("'", "&#39;");
        }
    }
    // @snippet:step3:end
}
